// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env'

export const environment = {
  production: true,
  version: env.npm_package_version,
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'lt-LT'
  ],
  databasePrefix: '',
  firebaseConfig: {
    apiKey: 'AIzaSyB_30SOIvf4tQx2V2ycqu_OY7_vvyge59E',
    authDomain: 'yet-another-tests.firebaseapp.com',
    databaseURL: 'https://yet-another-tests.firebaseio.com',
    projectId: 'yet-another-tests',
    storageBucket: 'yet-another-tests.appspot.com',
    messagingSenderId: '667627259862',
    appId: '1:667627259862:web:506581458c08f2e52b4677',
    measurementId: 'G-ZYB0Q765TM'
  }
}
